[general]
log_level = "debug"
log_location = "./log"
console_output = false


[mysql]
host = "localhost"
port = 3306
user = "mysql"
password = "mysql"


[udp]
ip_address = "192.168.178.43"
port = 8888